TechnicalAssessment/Controllers/DrowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TechnicalAssessment.Models;

namespace TechnicalAssessment.Controllers
{
    public class DrowController : Controller
    {
        // GET: Drow
        public ActionResult Index()
        {
            return View(new Drow("This is a Sample. 123. Of backwards Text."));
        }

        [HttpPost]
        public ActionResult Index(Drow Drow)
        {
            return View(Drow);
        }
    }
}

TechnicalAssessment/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TechnicalAssessment.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TechnicalAssessment/Controllers/ListTraverserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TechnicalAssessment.Models;

namespace TechnicalAssessment.Controllers
{
    public class ListTraverserController : Controller
    {
        // GET: ListTraverser
        public ActionResult Index()
        {
            LinkedList<int> list = new LinkedList<int>();
            list.AddLast(1);
            list.AddLast(2);
            list.AddLast(3);
            list.AddLast(4);
            list.AddLast(5);
            list.AddLast(6);
            list.AddLast(7);
            return View(new ListTraverser(list));
        }
        // GET: ListTraverser
        public ActionResult Index2(ListTraverser listTraverser)
        {
            return View(listTraverser);
        }
    }
}

TechnicalAssessment/Controllers/TriangulatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TechnicalAssessment.Models;

namespace TechnicalAssessment.Controllers
{
    public class TriangulatorController : Controller
    {
        // GET: Triangulator
        public ActionResult Index()
        {
            return View(new Triangulator(3, 4, 5));
        }

        [HttpPost]
        public ActionResult Index(Triangulator triangulator)
        {
            return View(triangulator);
        }
    }
}

TechnicalAssessment/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TechnicalAssessment/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TechnicalAssessment/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Technical Assessment";
}

<div class="jumbotron">
    <h1>Technical Assessment</h1>
    <p class="lead">Enjoying the journey....</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Trangulator</h2>
        <p>
            From the three entered parameters dertermine the type of Triangle. Options are:
        </p>
        <ol>
            <li>Right</li>
            <li>Acute</li>
            <li>Obtuse</li>
            <li>Equilateral</li>
            <li>Isoscles</li>
            <li>Scalene</li>
        </ol>
        <p>@Html.ActionLink("Try It Now!", "Index", "Triangulator")</p>
    </div>
    <div class="col-md-4">
        <h2>DroWord</h2>
        <p>This ia sentence backwardiser. Not Backwardising the sentence but the words within the entence.</p>
        <p>@Html.ActionLink("Try It Now!", "Index", "Drow")</p>
    </div>
    <div class="col-md-4">
        <h2>The -5th Element</h2>
        <p>Find the fifth element form the end of a linked list of elements.</p>
        <p>@Html.ActionLink("Try It Now!", "Index", "ListTraverser")</p>
    </div>
</div>